sudo: required
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- grunt
deploy:
- provider: firebase
  project: mvs-plugin-api
  token:
    secure: "QmD58RTxUzuf70CN9kwZuM8sakPE5lDgeGxPqsrtN0T+o3PWXjv3RP1ueOmQ2F6hVbDYeGuV86jF7kb32bfG+LnWonTXnvZFe+eJfUDcO+K4ajcIBME9TB2qZSya4NagyvzAwKPyuXHP0Ggp8sxKoF+OTVdfSUNHgLziORJYvxzioYXZZyLCJZc9Nn8URP+yIn4SU2TEyNmIIerFsr9pvBJ07vbIb/M6JNeaioknxclczFFwhDkYkNCpAybxQbA0Rw0Ez/5wlo69W+nM2VUYPiavgcPAGLpOxmtSN2vpdAqrSTMZc/EINqlTAU1Daw:Autoformatrzz/p9K2TXs4ZY/UwqA2M3NYU4cB5l+ZtxHX11N39i9ctiqUHO9gyjdHwOY5kaFIks8xiKBW6IITp5OL3ZuvMD69W3evAgIEX6xM//cw22HSk2TCc+G1XmvWKLguThO+2Cita5m3dUnnm81M6/o5hA/9TaSJ2L7sulqGbonR3Fv+njd5zpuGeARgJQayMmLE9s9Ol0Ze9nQ/vWu74paH7T/8NTICAdS0Boj8Y4ZluPWZgRp6usJuVNa/ozQIiF8t+LoZv85o2UxfiLVIgdstTR4TOawrpzmPg0dvw+PgTt/N3ORfpGG6ZiBq5RRWHD1TxgXRIBJnUFbVvBkSxuI/3klVMSjnY3cxDzn72REIcS0="
  skip_cleanup: true
  on:
    branch: master
